version: '3.8'

services:
  tdeed-evaluator:
    build: .
    env_file: .env
    volumes:
      - .:/app  # Mount current directory to /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 