version: '3.8'

services:
  tdeed-evaluator:
    build: .
    env_file: .env
    volumes:
      - .:/app  # Mount current directory to /app
    runtime: nvidia  # Enable NVIDIA runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs available
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 